version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

executors:
  ruby:
    docker:
      - image: cimg/ruby:2.6.3

jobs:
  build:
    executor:
      name: ruby
    steps:
      - run: |
          apt-get -y update
          apt-get -y install libmariadb-dev tzdata
      - aws-cli/install
      - checkout
      - run: |
          cat ~/.ssh/config
