version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3-browsers
    steps:
      - checkout
      - run: |
          bundle version
      - ruby/install-deps:
          app-dir: src
