version: 2.1

orbs:
  # Since 1.2.0, install-deps has been updated with `app-dir` arg.
  # See https://circleci.com/developer/orbs/orb/circleci/ruby?version=1.2.0#commands-install-deps
  ruby: circleci/ruby@1.8.0

jobs:
  test:
    docker:
      - image: cimg/ruby:3.0.3-browsers
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
    environment:
      APP_DATABASE_HOST: 127.0.0.1
    steps:
      - checkout
      - run: |
          bundle version
      - ruby/install-deps:
          app-dir: src
      - run:
          name: run DB migration
          command: bundle exec rails db:migrate
          working_directory: /home/circleci/project/src
      - run:
          name: test
          command: bundle exec rake test
          working_directory: /home/circleci/project/src
workflows:
  version: 2
  build_and_test:
    jobs:
      - test